In [1]:
from util import *

In [1]:
import numpy as np
import math
import copy
import torch
LARGEPRIME = 2**61-1
# torch.random.manual_seed(42)

In [2]:
n=100

In [3]:
np.random.seed(42)
stream = np.random.randint(1,n,size=n)
exactL2 = np.linalg.norm(stream, ord=2)

In [4]:
np.sort(stream)[::-1]

array([95, 93, 93, 92, 92, 91, 90, 90, 89, 89, 89, 88, 88, 87, 87, 85, 84,
       83, 82, 81, 80, 80, 78, 78, 76, 75, 75, 74, 73, 72, 72, 71, 64, 64,
       63, 62, 62, 62, 62, 62, 61, 60, 60, 60, 60, 59, 58, 55, 54, 54, 53,
       53, 53, 52, 51, 51, 50, 49, 48, 47, 47, 44, 44, 42, 40, 39, 38, 36,
       35, 34, 33, 30, 26, 24, 24, 22, 22, 21, 21, 21, 18, 18, 15, 15, 15,
       14, 14,  9,  8,  7,  6,  4,  4,  4,  3,  3,  2,  2,  2,  2])

In [5]:
stream, exactL2

(array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75, 88, 24,  3, 22, 53,  2, 88,
        30, 38,  2, 64, 60, 21, 33, 76, 58, 22, 89, 49, 91, 59, 42, 92, 60,
        80, 15, 62, 62, 47, 62, 51, 55, 64,  3, 51,  7, 21, 73, 39, 18,  4,
        89, 60, 14,  9, 90, 53,  2, 84, 92, 60, 71, 44,  8, 47, 35, 78, 81,
        36, 50,  4,  2,  6, 54,  4, 54, 93, 63, 18, 90, 44, 34, 74, 62, 14,
        95, 48, 15, 72, 78, 87, 62, 40, 85, 80, 82, 53, 24, 26, 89]),
 583.0583161228386)

In [124]:
c=2
r=100
d, k=None, None
device='cuda'
streamTr=torch.tensor(stream, dtype=torch.int64)
item=streamTr[2]
streamTr0=streamTr[:10]

In [123]:
run(streamTr, c, r, device)

tensor([7.0583], device='cuda:0')
tensor([10.3368,  7.0679], device='cuda:0')
tensor([12.3282,  7.0583], device='cuda:0')
tensor([13.9998,  7.0679], device='cuda:0')
tensor([15.2962,  9.9995,  7.0707], device='cuda:0')
tensor([16.5551, 10.0990,  7.0707], device='cuda:0')
tensor([17.9938,  9.8990,  7.0707], device='cuda:0')
tensor([18.6862,  9.5894,  7.0707], device='cuda:0')
tensor([19.4651,  9.8949,  7.0679], device='cuda:0')
tensor([22.5514, 14.1358,  7.0679], device='cuda:0')
tensor([23.4135, 15.4092,  9.6816,  7.0679], device='cuda:0')
tensor([24.8781, 12.7124, 10.2395,  7.0654], device='cuda:0')
tensor([25.4337, 14.6603, 12.5698,  7.0536], device='cuda:0')
tensor([26.5432, 13.6746,  9.3754,  7.0679], device='cuda:0')
tensor([28.2356, 16.2268, 12.1611,  7.0353], device='cuda:0')
tensor([28.2168, 17.9357, 14.0340,  7.0622], device='cuda:0')
tensor([31.0121, 16.3697, 10.2791,  7.0679], device='cuda:0')
tensor([31.5767, 17.4596, 12.2045,  7.0622], device='cuda:0')
tensor([31.7520, 18.

tensor([100.6223,  54.5115,  38.9238,  21.2124,  13.9641,   7.0707],
       device='cuda:0')